
services:

  app:
    #build: ./app
    image: mariavjs/projeto-cloud-242:latest
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
    #ports:
      # - "5432:5432"
