apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
    owner: mariavjs
spec:
  type: LoadBalancer  # Exposição externa via LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    owner: mariavjs
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
